# -*- coding: utf-8 -*-
"""KB_ChromaDB RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiYWQm9FN-4AwovpNzHWHfy2vFp7y9hs
"""

!pip install -q chromadb openai

#Step 1: Raw Data
from google.colab import files
uploaded= files.upload()

filename=list(uploaded.keys())[0]

with open(filename,'r') as file :
  knowlwdge_base= file.read()
print(knowlwdge_base)

#Step2 : Split knowledge base into chunks
def chunk_text(text,chunk_size=20):
  words= text.split()
  chunks=[]
  for i in range(0,len(words),chunk_size): #chunk_size is step
    chunk= " ".join(words[i:i+chunk_size])
    chunks.append(chunk)
  return chunks

knwoledge_chunks= chunk_text(knowlwdge_base,10)
print(knwoledge_chunks)

import openai
from openai import OpenAI
from google.colab import userdata

openai_key = userdata.get('OpenAI_API').strip()
client = OpenAI(api_key=openai_key)
def get_embeddings(text):
  response= client.embeddings.create(model="text-embedding-3-small",input=text)
  return response.data[0].embedding

#Step 4: vector DB- Chromadb
import chromadb
from chromadb.config import Settings

# client = chromadb.CloudClient(
#   api_key='YOUR_API_KEY',
#   tenant='b995643f-0943-47a8-b132-67d81a5d11da',
#   database='Simple Rag Application'
# )
import chromadb
chroma_client=chromadb.Client(Settings(persist_directory="./chrom_store"))
collection=chroma_client.get_or_create_collection(name="my-kb")

for i,chunk in enumerate(knwoledge_chunks):
  # print(chunk)
  collection.add(
      ids=[f"chunk-{i+1}"],
      documents=[chunk],
      embeddings=[get_embeddings(chunk)]
  )

query="how many overs in test match"
query_emb=get_embeddings(query)
results=collection.query(
    query_embeddings=[query_emb],
    n_results=2
)
print(results)

context="\n".join(results)

response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {
            "role":"system","content":"your are help Ai assitance, query only asked"
        },
        {
            "role":"user","content":f"Context: {context}\n\nQuestion : {query}"}
    ])
print(response.choices[0].message.content)