# -*- coding: utf-8 -*-
"""RAG_policyAssingment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQZI9MY5O2eBLgGCZCsVi0tZMXm-PAW1
"""

#Step1 : Load Raw Data
RAW_POLICY="""
Work Hours: Employees must work 8 hours per day. Flexible timings allowed between 8 AM to 8 PM.
Remote Work: Employees can work remotely up to 3 days per week with manager approval.
Overtime: Paid overtime applies after 9 hours of work. Must be pre-approved.
Dress Code: Smart casuals from Monday to Thursday. Casual wear allowed on Fridays.
Internet Usage: Company internet must be used responsibly. Streaming services allowed only during breaks.
Security: Company laptops must be locked when unattended. Password change is required every 45 days.
"""

#Step 2: Break down Raw data intonchunks
def chunk_policy(raw_text):
  chunks=[]
  for doc in raw_text.strip().split("\n"):
    clean_line=doc.strip()
    if clean_line:
      chunks.append(clean_line)
      # print("CHUNKS:",chunks)
  return chunks

chunks = chunk_policy(RAW_POLICY)
print("Final Chunks:", chunks)

#Step 3: keyword search logic
def search_chunks(chunks,user_query):
  query=user_query.lower()
  matched_chunks=[]
  # print("Query:",query)
  for chunk in chunks:
    if query in chunk.lower():
      matched_chunks.append(chunk)

  return matched_chunks

#Step 4: Generate Answer
def generate_answer(matched_chunks,question):
  if not matched_chunks:
    return "I don't know based on the provided context."

  context = " ".join(matched_chunks)
  return f"{context}\n(This answer is based only on the provided context.)"

#Step 5: All Together
def main(question):
  chunks=chunk_policy(RAW_POLICY)
  matched_date=search_chunks(chunks,question)
  answer=generate_answer(matched_date,question)
  return answer

print(main("overtime"))

print(main("leave policy"))

from google.colab import drive
drive.mount('/content/drive')

from zipfile import ZipFile

import os
from zipfile import ZipFile

# Define the file to be zipped and the name of the output zip file
file_to_zip = '/content/drive/MyDrive/Colab Notebooks/RAG_policyAssingment.ipynb'
zip_file_name = 'RAG_policyAssingment.zip'

# Create a ZipFile object in write mode
with ZipFile(zip_file_name, 'w') as zipf:
    # Add the file to the zip archive. The second argument is the arcname (name inside the zip file).
    # Using os.path.basename to keep the original filename inside the zip.
    zipf.write(file_to_zip, os.path.basename(file_to_zip))

print(f"File '{file_to_zip}' has been successfully zipped into '{zip_file_name}'")
print(f"You can find the zip file at: {os.path.abspath(zip_file_name)}")

"""!"""

!pip install numpy
from openai import OpenAI
import numpy as np
from google.colab import userdata
openapi_key=userdata.get("OpenAI_API")

def get_embedding(word):
  # Strip any leading/trailing whitespace from the API key
  client=OpenAI(api_key=openapi_key.strip())
  response=client.embeddings.create(model="text-embedding-3-small",input=word)
  return response.data[0].embedding

def cosine_compare(vec1,vec2):
  return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
vector1=get_embedding('cat')
vector2=get_embedding('dog')
compare_value=cosine_compare(vector1,vector2)
print("Cosine simailary:",compare_value)